# Generated by Django 4.2.3 on 2024-05-16 16:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('title1', models.CharField(max_length=200)),
                ('point1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('point2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('point3', models.CharField(max_length=200)),
            ],
        ),
    ]
