# Generated by Django 4.2.3 on 2024-05-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
