# Generated by Django 4.2.3 on 2024-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0005_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('', 'Choose your role'), ('highereducation', 'highereducation'), ('student', 'student '), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
