# Generated by Django 5.0.4 on 2024-05-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_Name', models.CharField(max_length=80)),
                ('college_Country', models.CharField(max_length=20)),
                ('college_City', models.CharField(max_length=50)),
                ('college_Subcity', models.CharField(max_length=80)),
                ('college_Email', models.EmailField(max_length=254, unique=True)),
                ('college_Description', models.CharField(max_length=500)),
                ('college_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College_Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field_Name', models.CharField(max_length=100)),
                ('Field_Branch', models.CharField(choices=[('NS', 'Natural Science'), ('SS', 'Social Science')], max_length=2)),
                ('Field_Category', models.CharField(choices=[('Engineering', 'Engineering'), ('Health', 'Health'), ('IT', 'IT'), ('Business', 'Business'), ('History', 'History')], max_length=20)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finapp.college_list')),
            ],
        ),
        migrations.CreateModel(
            name='College_Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matric_Requirement', models.CharField(max_length=10)),
                ('GPA_Requirement', models.CharField(max_length=10)),
                ('ExtraCurricular_Requirement', models.CharField(max_length=300)),
                ('Rcollege', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finapp.college_list')),
            ],
        ),
    ]
